GET http://localhost:3000/tasks

###
POST http://localhost:3000/tasks
content-type: application/json

{
  "title": "Fazer chá",
  "description": "Colher hortelã e fazer chá"
}


###
PUT  http://localhost:3000/tasks/1
content-type: application/json

{
  "title": "Lavar louça",
  "description": "Lavar louça do chá de ontem"
}


###
PATCH http://localhost:3000/tasks/1/complete


###
PATCH http://localhost:3000/tasks/1/incomplete

###
DELETE http://localhost:3000/tasks/1