GET http://localhost:3000

###
GET http://localhost:3000/tasks

###
POST http://localhost:3000/tasks HTTP/1.1
content-type: application/json

{

  "title": "Estudar NestJS",
  "description": "Continuar o projeto de tarefas",
  "date": "2026-01-19",
  "completed": false

}


###
PATCH http://localhost:3000/tasks

###
PUT http://localhost:3000/tasks

###
DELETE http://localhost:3000/tasks